### ISSUE TITLE
A few outdated modules

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-oauth-console#18]
### Steps to reproduce
```
$ npm run outdated

> fxa-oauth-console@0.3.4-pre outdated /Users/pdehaan/dev/github/fxa-oauth-console
> npm outdated --depth 0
```

| Package                    | Current         | Wanted           | Latest  | Location |
|----|----:|----:|----:|----|
| bluebird              |      2.3.11      |   2.3.11       |     2.6.4 | bluebird
| body-parser          |       1.10.0       |  1.10.0    |       1.10.1|  body-parser
| broccoli-asset-rev      |     2.0.0      |    2.0.0       |     2.0.1 | broccoli-asset-rev
| convict                   |   0.6.1      |    0.4.2       |     0.6.1|  convict
| ember-cli                  |  0.1.7      |    0.1.4       |     0.1.7 | ember-cli
| ember-cli-qunit           |   0.1.1       |   0.1.1     |       0.1.2 | ember-cli-qunit
| ember-data       |    1.0.0-beta.12 | 1.0.0-beta.12 | 1.0.0-beta.14.1|  ember-data
| express                  |   4.10.6     |    4.10.6    |       4.10.8|  express
| glob                 |        4.3.1         | 4.3.1     |       4.3.4 | glob
| load-grunt-tasks       |      1.0.0    |      1.0.0    |        2.0.0 | load-grunt-tasks
| nodemon                |      1.2.1     |   1.3.0-7         |   1.2.1 | nodemon
| selenium-standalone   |      2.44.0     |    2.44.0      |      3.0.3  |selenium-standalone
| xmlhttprequest             |  1.5.1       |     git      |        git | xmlhttprequest

A few of these look a bit "stale", notably these:

```
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp audit-shrinkwrap
Name          Installed   Patched  Vulnerable Dependency
qs              0.6.6     >= 1.x   fxa-oauth-console > bower > bower-registry-client > request
qs              0.6.6     >= 1.x   fxa-oauth-console > bower > bower-registry-client > request
validator       1.5.1    >=3.22.1  fxa-oauth-console > convict
validator       1.5.1     >=2.0.0  fxa-oauth-console > convict
qs              0.6.6     >= 1.x   fxa-oauth-console > ember-cli > bower > bower-registry-client > request
qs              0.6.6     >= 1.x   fxa-oauth-console > ember-cli > bower > bower-registry-client > request
serve-static    1.7.1     >=1.7.2  fxa-oauth-console > ember-cli > express
connect         2.7.2     >=2.8.1  fxa-oauth-console > ember-cli > testem > express
qs              0.5.1     >= 1.x   fxa-oauth-console > ember-cli > testem > express > connect
qs              0.5.1     >= 1.x   fxa-oauth-console > ember-cli > testem > express > connect
send            0.1.0    >= 0.8.4  fxa-oauth-console > ember-cli > testem > express
```

If I bump `convict` and `ember-cli` to their latest versions, and re-shrinkwrap and re-run `nsp`, then that only leaves these results:

```
Name          Installed   Patched  Vulnerable Dependency
qs              0.6.6     >= 1.x   fxa-oauth-console > bower > bower-registry-client > request
qs              0.6.6     >= 1.x   fxa-oauth-console > bower > bower-registry-client > request
qs              0.6.6     >= 1.x   fxa-oauth-console > ember-cli > bower > bower-registry-client > request
qs              0.6.6     >= 1.x   fxa-oauth-console > ember-cli > bower > bower-registry-client > request
```

I'd file a Bower bug to update that pesky (and vulnerable) module, but... https://github.com/bower/bower/issues/1452

Also (just to make this the _worst_ bug report of all times), I noticed that we have `ember-cli` listed as a dependency AND a devDependency. Both use `"ember-cli": "0.1.4",` so it isn't a huge deal, but it did blow up my attempt at rerunning shrinkwrap after running `npm i ember-cli@latest -S` since I was then trying to install 0.1.4 and 0.1.7 and shrinkwrap really didn't like that. Manually removing it as a devDependency and then rerunning `npm shrinkwrap --dev` worked like a champ though.

**Comment by vladikoff** [comment]
updated a lot of these in https://github.com/mozilla/fxa-oauth-console/commit/d40ceaf2e665c0387d2646033777969d93e2a502
