### ISSUE TITLE
Ship OAuth management console to production

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-console#19]
Meta bug for shipping this management tool to production.

- [x] Get CLI in Ops hands
- [x] Implement Client Owners
- [ ] Deploy Client Owners to production
- [ ] Add owners to current clients (@ckarlof, @ckolos, @jrgm?)
- [x] Remove `prod` guard from OAuth Server

- behind a mozilla-only security wall of some kind (e.g. VPN only access)

**Comment by vladikoff** [comment]
"Implement Client Owners" done

**Comment by vladikoff** [comment]
@rfk should we close this for now because we are focused on other things and not third-party relier management ?

**Comment by rfk** [comment]
Yes, our attention is elsewhere for the next little while, let's close this out
