### ISSUE TITLE
cannot create a new client (oauth hapi validation rejecting payload with null secret)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-console#21]
I updated stable with the fix from https://github.com/mozilla/fxa-oauth-server/pull/223 and was trying to use the console at https://oauth-stable.dev.lcip.org/console.

On either stable or https://oauth-latest.dev.lcip.org/console, when I try to create a client (POST /v1/client), I get a response of '400 Bad Request' for 'Invalid request parameter' naming 'secret' as the problem key.

The request body is '
```
{
  "name":"jrgm test",
  "redirect_uri":"http://127.0.0.1/",
  "image_uri":"http://127.0.0.1/",
  "secret":null,
  "can_grant":false,
  "whitelisted":true
}
```

**Comment by vladikoff** [comment]
thanks for reminding me, fixed in 0.3.5!
