### ISSUE TITLE
Consols are offline?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#22]
We can't reach http://oauth-latest.dev.lcip.org/console/ nor https://oauth-stable.dev.lcip.org/console to create new OAuth client tokens to add FxA Auth to http://browsercompat.herokuapp.com/.

**Comment by groovecoder** [comment]
Tag @jwhitlock on this too ...

**Comment by rfk** [comment]
They appear to be up for me now; @groovecoder it's not obvious from the UI, but you need to use an @mozilla.com address when authenticating, could this be the source of the problem?

**Comment by groovecoder** [comment]
Still can't reach them ...

![oauth-latest](https://cloud.githubusercontent.com/assets/71928/6333231/0543dc7e-bb51-11e4-8a4f-61f219a67f79.png)

![oauth-stable](https://cloud.githubusercontent.com/assets/71928/6333237/0c13e116-bb51-11e4-8235-b58932c78729.png)

**Comment by rfk** [comment]
Maybe a http/https issue, can you please try adding https:// explicitly?

**Comment by rfk** [comment]
(I don't think these machines even listen on port 80)

**Comment by groovecoder** [comment]
Bah, that was it. Not sure how I got linked to the http urls. https://developer.mozilla.org/en-US/Firefox_Accounts_OAuth_Dashboard has the right links. Weird ... sorry for the noise.

**Comment by rfk** [comment]
I filed https://github.com/mozilla/fxa-dev/issues/118 to investigate adding a redirect here; I frequently hit this problem and take a few moments to remember what's causing it.
