### ISSUE TITLE
Login infinite redirect

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#23]
I tried to access the console at https://oauth-latest.dev.lcip.org/console/
I tried a few different passwords
I got "Client has sent too many requests" error
I clicked "Forgot password"
I reset my password
I went back to https://oauth-latest.dev.lcip.org/console/login
I entered my new password

Expected results:
https://oauth-latest.dev.lcip.org/console/

Actual results:
I bounce thru /auth/v1/account/login, /console/, /console/oauth/logout, and I land back on /console/login

**Comment by vladikoff** [comment]
Hey @groovecoder, 

did you make sure to create a new account on the dev environment and make sure to use a "@mozilla.com" email address?

> To login to this console you must create and verify a Firefox Account on this oauth-latest.dev.lcip.org development server.
Only @mozilla.com emails are allowed to login to this console.

**Comment by groovecoder** [comment]
Yes. I made an account and already some developer FxA credentials on the dashboard. I'm trying to get back into it to get my client ID and secret.

**Comment by vladikoff** [comment]
@groovecoder 

![image](https://cloud.githubusercontent.com/assets/128755/6577679/0004d684-c716-11e4-87ba-fc8e71494813.png)

Ah I see there is an issue on latest with the oauth server.

Could you please use the stable environment? See https://oauth-stable.dev.lcip.org/console/clients

**Comment by vladikoff** [comment]
You will have to recreate the client on `stable` but you will get a more STABLE experience with that one :)

**Comment by ckarlof** [comment]
@groovecoder, I was able to log into the "stable" environment. "latest" can be flaky. Everything in latest is continuously and automatically updated from master. I'd only recommend using it if you absolutely need to do some integration testing with something that isn't yet in prod.

**Comment by groovecoder** [comment]
I tried signing up on stable and I never got the email verification?

**Comment by vladikoff** [comment]
@groovecoder check the spam / junk folder? I just recreated my @mozilla.com account and got an email

**Comment by seanmonstar** [comment]
@vladikoff also seems like the Console isn't correctly handling the 404 to the clients endpoint?

**Comment by vladikoff** [comment]
@seanmonstar currently it will log the user out unless the api returns 200

**Comment by groovecoder** [comment]
So, the email from stable server went to spam, which seems like another bug, so I filed https://github.com/mozilla/fxa-oauth-console/issues/26.

I was able to create the client on stable, but then I ran into https://github.com/mozilla/fxa-oauth-console/issues/25 trying to use the client.

Closing this issue in favor of those others.
