### ISSUE TITLE
Create client without image_uri responds with error but no UI

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#24]
Steps to reproduce:
1. Go to create a new client (https://oauth-stable.dev.lcip.org/console/client/register)
2. Omit the Image URI

Expected Results:
* Create the client without an image
**or**
* Show an error message that image is required

Actual Results:
Nothing, and this is in the log:
```
{"code":400,"errno":109,"error":"Bad Request","message":"Invalid request parameter","info":"https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors","validation":{"source":"payload","keys":["image_uri"]}}
```

**Comment by vladikoff** [comment]
Thanks for the report! Will fix in the next version

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-oauth-console/commit/e8a945b34b089ebedf892d76cc145ae0751d875e
