### ISSUE TITLE
New client ID isn't working with django-allauth

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#25]
@jwhitlock [apparently got this working](https://github.com/mozilla/web-platform-compat/pull/21#issuecomment-78073054) for his instance of web-platform-compat, but here's what I tried ...

Steps to reproduce:
1. Create a brand new client at https://oauth-stable.dev.lcip.org/console/clients (mine is https://oauth-stable.dev.lcip.org/console/client/fa35c5aaaa8aebc7)
2. Copy the FxA credentials into django-allauth db
3. Try to sign in with Firefox Account

Expected results:
Sign in works

Actual results:
Generic "Bad request" page: https://accounts.firefox.com/400.html?message=Unknown%20client&errno=101&namespace=oauth

When I look at [my client in the console](https://oauth-stable.dev.lcip.org/console/client/fa35c5aaaa8aebc7/update), I notice "Whitelisted Client: (Currently required for all clients)" is **un-checked**. When I check it and click "Update", it doesn't seem to save?

**Comment by jwhitlock** [comment]
@groovecoder - you need to check against https://oauth-stable.dev.lcip.org/v1, not https://accounts.firefox.com.  Did you ``export FXA_OAUTH_ENDPOINT=https://oauth-stable.dev.lcip.org/v1; export FXA_PROFILE_ENDPOINT=https://stable.dev.lcip.org/profile/v1`` and restart your server w/ the new config?

**Comment by ckarlof** [comment]
@jwhitlock is correct. Here are all the relevant endpoints for the stable dev environment:

https://developer.mozilla.org/en-US/Firefox_Accounts#Stable_development_%28production_clone%29

`accounts.firefox.com` is the FxA production login page (i.e., the UI for logging in).
