### ISSUE TITLE
Account emails are sent to "Spam"

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#26]
Steps to reproduce:
Sign up for an account on stable: https://oauth-stable.dev.lcip.org/console/clients

Expected results:
Email verification should show up in my Inbox

Actual results:
Email verification went to my Spam

**Comment by seanmonstar** [comment]
Technically, the email comes from the content-server. I'll move this.

**Comment by shane-tomlinson** [comment]
> Technically, the email comes from the content-server. I'll move this.

Technically, these come from the [fxa-auth-mailer](https://github.com/mozilla/fxa-auth-mailer/).

**Comment by seanmonstar** [comment]
:D Move it wherever
