### ISSUE TITLE
require redirect_uri in the client registration form

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-console#33]
Part of https://github.com/mozilla/fxa-oauth-server/issues/230

**Comment by shane-tomlinson** [comment]
@vladikoff: Is this in progress, or should it be moved back to "ready"?

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-oauth-console/commit/d989202fcc913fee3fbb7f5b16fe139b11fce29c
