### ISSUE TITLE
ember-cli reported as a dependency and devDependency

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-console#36]
```
npm WARN package.json Dependency 'ember-cli' exists in both dependencies and devDependencies, 
using 'ember-cli@1.13.8' from dependencies
```

**Comment by vladikoff** [comment]
This *was* "by design", I filed an issue https://github.com/ember-cli/ember-cli/issues/2207. 

But looks like it was fixed in https://github.com/ember-cli/ember-cli/pull/3015 so I fix this up
