### ISSUE TITLE
redirect_uri should be trimmed for whitespace

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-console#37]
I copy/pasted a redirect_uri into the OAuth console last week and was later informed by the developer the redirect_uri had an unexpected space at the end when redirecting back to their site. Sure enough, I went back into the console and a space was at the end of the redirect_uri.  `redirect_uri` should be `trim`ed to remove leading and trailing whitespace.

**Comment by vladikoff** [comment]
Fixed!
