### ISSUE TITLE
Can't register new client: js error

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#39]
Steps to reproduce:
0. (Maybe) Stay out of the dev console for a really long time - trigger a session timeout?
0. (Maybe) Sign in to the dev console with a non-@mozilla.com email address?
1. Go to https://oauth-stable.dev.lcip.org/console/client/register
2. Enter values
  * Client Name: Moz Push Service Dev Dashboard (Local)
  * Redirect URI: http://127.0.0.1:8000/accounts/fxa/login/callback/
3. Click Create

Expected results:
Show the client secret and sample configuration

Actual results:
Big js stacktrace in console error log.

**Comment by vladikoff** [comment]
Thanks for the issue!
