### ISSUE TITLE
Question: Is this front-end a good model for more service consoles? 

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa-oauth-console#41]
We're working on a developer console for the push service. We're starting to [create our base template and UI](https://github.com/groovecoder/push-dev-dashboard/pull/26).

I like the design here, but I notice it's using Ember? How is the Ember code? Should we look at something else?

**Comment by vladikoff** [comment]
> I like the design here, but I notice it's using Ember? How is the Ember code? Should we look at something else?

The design is a mix of suggestions from FxA designers and [Foundation 5 css](http://foundation.zurb.com/)

If you want FxA OAuth Integration and not afraid of Ember then you can use it. You can also just take the CSS and not the JS bits. Let me know if you have other questions
