### ISSUE TITLE
Support "sharing" created clients with team members

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-console#55]
AMO makes changes to their OAuth clients (changes redirect uri, etc) and asked for client sharing

> [10:11:53]  <eviljeff>	vladikoff: is there a way generally to get access to clients other people have created?  It would be better if multiple people could change it rather than having to create a new one each time someone leaves / is on PTO

**Comment by andymckay** [comment]
Do we get a lot of change requests coming through on this?

**Comment by rfk** [comment]
Not too many, although I hope we get more as 2018 goes on.  The process is just pretty manual right now in prod, see e.g. https://github.com/mozilla/fxa-oauth-server/issues/515 and https://github.com/mozilla/fxa/issues/282 and the various bugs spawned off them.  It's manageable, but we should expect it to become less so as the number of reliers grows.

**Comment by vladikoff** [comment]
> Do we get a lot of change requests coming through for this?

Nope, maybe 1-2 in ~4-5 months, but we can revisit this if we are planning to expand the oauth-console usage

**Comment by vladikoff** [comment]
Didn't have any requests for this recently, closing for now 🗡
