### ISSUE TITLE
Is this repository still used?

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa-oauth-console#78]
The readme for this repository says:
> This repository has been migrated to https://github.com/mozilla/fxa/tree/master/packages/fxa-oauth-console
> Please file issues and open pull requests against https://github.com/mozilla/fxa

But that's a 404 and all the other repositories that got pulled in to the monorepo were archived.  Is this repository still used? /cc @shane-tomlinson @dannycoates

**Comment by vladikoff** [comment]
yes, we moved it back into this repo out of the mono repo, we can possibly restore the readme.

**Comment by clouserw** [comment]
Thanks.  I opened https://github.com/mozilla/fxa-oauth-console/pull/79

**Comment by vladikoff** [comment]
To help maintain and write new features for this we are planning to rewrite some parts of the console in the future, just FYI
